### PR TITLE
Create lo1 interface without reboot, add start action

### PR DESCRIPTION
**Pull request by sekrett**

### CODE REVIEW

**Comment by sekrett** [comment]
The rc.d script is used to start jails after reboot, you don't need to call it before any jail is created. It even causes error if called twice. The jail itself should be started in a different way.

**Comment by sekrett** [comment]
I don't understand your regexp and I believe it does not work (maybe it worked with a previous version of ezjail). I think that grepping for jail name and ip address should be safe, the names may overlap but ip address are always unique.

**Comment by brkane** [comment]
Finally got a chance to test this. All looks to work. If this is ready to merge, can you bump the version?

**Comment by sekrett** [comment]
Yes, it is ready, I use it on real servers now. It would be great to add documentation and push it to supermarket, maybe next time. :)

**Pull request merged**
